# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Premier Post-Quantum Security Suite: Hybrid HPKE (ML-KEM + X25519) encryption."
  homepage "https://github.com/al-Zamakhshari/maknoon"
  version "1.1.76"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.1.76/maknoon_1.1.76_darwin_amd64.tar.gz"
      sha256 "feb26550541931951fbcf5a2deea5b22fcfd2ee1c6321c6c49eac2c6473cb844"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.1.76/maknoon_1.1.76_darwin_arm64.tar.gz"
      sha256 "169cebffb18df471ce2e84f56133991aa89ca38c64ff59d22b161e65ba702107"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.1.76/maknoon_1.1.76_linux_amd64.tar.gz"
      sha256 "ab48908304fb03ff511d89c69d2ab585ff0ca558e988f164adf75a51a7d47b93"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.1.76/maknoon_1.1.76_linux_arm64.tar.gz"
      sha256 "9e2b2d8f23717c356493795dad79b55a5c37f08043f805d15ed5ff99de429617"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
