# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.72"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "7b1c9f43b037b0c24353964e7ef26cb9ffa38733fd92f9e962a77ab8d4a39ee1"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "c891ce8bd4f2359b6027821a656e30d33f84d838d3ed1288ed8029850ee7ab8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "be52f07b96732cc823de3869b4a7d195d04b30016da783c3c8170871655a9b83"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "a22f3babfeb712ff88255633f704d254bed796cb1eadf7b77f883a4cdfb47534"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
