# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.68"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "d3892c21cfe6bcc6f54d6ac10b08350034340c89ed9ab3de3ee8128450115a8d"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "7d695c3d5483994ba8e869585b1f50a864e6491f96705cd4b90a33ccbd27cd0c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "662af06a9f4cfd1ee1bbab71226a51a44f99e666e741702f2b9d5fc2fac5ed1d"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "2f885533b7f69866f38c1bf457df5b94ac229a64a126b320d01c48a7ec4fd9c5"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
