# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.58"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "10626361e73c6156c0fc9202716adaa1fec84b9050108cb1800fd4072abe4e3d"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "a6bd5c503914cd76ad29b12f54b644f2646e3c5f65451aca8c44a184d9973761"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "a9825e6216dbfb33c28fe71661723eef839a90659e241e394fc9e096ca552c8a"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "e0a49b105c01f046343d1032d655b4c1e312625c2917f65c3c5577939c3d0ee5"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
