# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Post-quantum cryptography CLI and MCP server. Hybrid ML-KEM/X25519 encryption, ML-DSA-87 signatures, encrypted vault, and identity publishing via WKD/DNS."
  homepage "https://github.com/al-Zamakhshari/maknoon"
  version "1.3.148"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.148/maknoon_1.3.148_darwin_amd64.tar.gz"
      sha256 "c8c86164809258c3927de78e468701fde3d64782f9cabe320c18b902347e9068"

      define_method(:install) do
        bin.install "maknoon"
        man1.install Dir["man/*.1"]
        bin.install_symlink bin/"maknoon" => "mkn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.148/maknoon_1.3.148_darwin_arm64.tar.gz"
      sha256 "50355fe759eadc80164ae8aaf501e4087e2b11e8c83052cf1ba01ad1a45b8a41"

      define_method(:install) do
        bin.install "maknoon"
        man1.install Dir["man/*.1"]
        bin.install_symlink bin/"maknoon" => "mkn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.148/maknoon_1.3.148_linux_amd64.tar.gz"
      sha256 "0f059c2bba23e5585e75fc16098531fb96c5f2807ee6149333ea6281ddf4089b"
      define_method(:install) do
        bin.install "maknoon"
        man1.install Dir["man/*.1"]
        bin.install_symlink bin/"maknoon" => "mkn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.148/maknoon_1.3.148_linux_arm64.tar.gz"
      sha256 "3518c900849630c2479b3a8276b698bb6c06b1f50c95dbe7390d6f4733ff799f"
      define_method(:install) do
        bin.install "maknoon"
        man1.install Dir["man/*.1"]
        bin.install_symlink bin/"maknoon" => "mkn"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
