# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Premier Post-Quantum Security Suite: Hybrid HPKE (ML-KEM + X25519) encryption."
  homepage "https://github.com/al-Zamakhshari/maknoon"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.1/maknoon_1.3.1_darwin_amd64.tar.gz"
      sha256 "3c3a4cf370b452c2fb9f33ccfc7973b3901aa7f8eb1fca56c868fc30682c7a50"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.1/maknoon_1.3.1_darwin_arm64.tar.gz"
      sha256 "f8f9f2844866bbdfe2b5e1e9023a7f8ee6ccdd52b27e22b8520f911b6ff30bae"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.1/maknoon_1.3.1_linux_amd64.tar.gz"
      sha256 "cb57d3e08baa0304dc3d14d55ce91d7e3d901a302af07d7f2cc78d1bfa381ff2"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.1/maknoon_1.3.1_linux_arm64.tar.gz"
      sha256 "850ea8ecf4feeef1ca59fbfd6545bfd95394c6f7c0cb0054a373f313d70de294"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
