# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Premier Post-Quantum Security Suite: Hybrid HPKE (ML-KEM + X25519) encryption."
  homepage "https://github.com/al-Zamakhshari/maknoon"
  version "1.3.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.12/maknoon_1.3.12_darwin_amd64.tar.gz"
      sha256 "156b2a5472e4b977a1861725b46df957f251b566efbf2beb6abf9ff78fb59ad1"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.12/maknoon_1.3.12_darwin_arm64.tar.gz"
      sha256 "3ccc82270676479df731df450cae4c8557d228701d78db96e4a84292fa9a8791"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.12/maknoon_1.3.12_linux_amd64.tar.gz"
      sha256 "eed4e8b5ec977cf86d5ffd167706f5ed35a18e4d93759cc6c251b47e1d6f6a33"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.3.12/maknoon_1.3.12_linux_arm64.tar.gz"
      sha256 "2fe61555df58b2dd51c86110126b231d0d678c1a27467a2c52e55ed07ac13b37"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
